name: Develop pipeline

on:
  pull_request:
    branches:
      - develop
    types: [opened, synchronize, reopened, closed]

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.18
          cache: 'npm'

      - name: Install project dependencies
        run: npm ci --prefer-offline

      - name: ESLint
        run: npm run lint

  format:
    name: Prettier
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.18
          cache: 'npm'

      - name: Install project dependencies
        run: npm ci --prefer-offline

      - name: Prettier
        run: npm run prettier
