name: Prod frontend deploy

needs: Stage-frontend-build-and-deploy
#on:
#  workflow_run:
#    workflows: ["Stage-frontend-build-and-deploy"]
#    types:
#      - completed

on:
  pull_request:
    branches:
      - develop
#    types: [ closed ]


env:
  REGISTRY: ghcr.io
  REP_OWNER: studio-yandex-practicum
  IMAGE_NAME: lomaya_baryery_frontend
  DEPLOY_PATH: /lombarye/full
  WORK_DIR: /LOMAYA_BARYERY_FULL

defaults:
  run:
    working-directory: .

jobs:
  deploy_and_start_application:
    name: Deploy and start application on prod
    runs-on: ubuntu-latest
    environment:
      name: prod_deploy
    steps:
      - name: Deploy and start application on prod
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ${{ env.DEPLOY_PATH }}
            docker image prune -f
            docker pull  ${{ env.REGISTRY }}/${{ env.REP_OWNER }}/${{ env.IMAGE_NAME }}:latest
            docker-compose --file docker-compose.yaml stop
            docker-compose --file docker-compose.yaml rm frontend
            docker-compose --file docker-compose.yaml up -d
